BINS=main.elf 

# put here the additional .o files you want to generate
# one .c file for each .o should be present
OBJS=./utils/uart.o
OBJS+=./utils/analog.o

# put here the additional header files needed for compilation
HEADERS=./utils/uart.h
HEADERS+=./utils/analog.h


# the file below contains the actual rules

# !!!!!!!!!!!!!!!! MODIFY HERE !!!!!!!!!!!!!!!! 

include ./utils/avr.mk




